# Generated by Django 4.0.6 on 2022-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(default=2010, verbose_name='개봉년도'),
            preserve_default=False,
        ),
    ]
