# Generated by Django 4.0.6 on 2022-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_Title', models.CharField(max_length=100, verbose_name='아이디어 제목')),
                ('idea_Content', models.TextField(verbose_name='아이디어 설명')),
                ('idea_Interest', models.IntegerField(verbose_name='관심도')),
                ('idea_Devtool', models.CharField(max_length=50, verbose_name='예상 개발툴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dev_Title', models.CharField(max_length=100, verbose_name='개발툴 제목')),
                ('dev_Type', models.CharField(max_length=50, verbose_name='종류')),
                ('dev_Content', models.TextField(verbose_name='개발툴 설명')),
            ],
        ),
    ]
